/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BtnTransparent: typeof import('./src/components/BtnTransparent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PopularVideos: typeof import('./src/components/PopularVideos.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
